### ISSUE TITLE
NullPointerException crash 

### ISSUE THREAD

**Issue by jonasbark** [tuya/tuya-android-industry-app-sdk-sample#8]
Hi there!

I'm not sure what exactly happened as it has worked fine before. All we did was adjust the App Authorizations to use a new application ID.

This is all the code that we use:
```
TuyaIoTSDK.builder().init(applicationContext as Application, appKey, appSecret)
            .hostConfig(RegionHostConst.REGION_HOST_EU)
            .debug(true)
            .build()

TYActivatorManager.activator.getRegistrationToken(
            assetId,
            "AP",
            IoTCommonUtil.getTimeZoneId(),
            "",
            object : ResultListener<RegistrationTokenBean> {
                override fun onFailure(errorCode: String?, errorMsg: String?) {
                    result.error(IOException("$errorCode $errorMsg"))
                }

                override fun onSuccess(bizResult: RegistrationTokenBean?) {
                    result.success(TuyaSdkGenerated.PairingToken().apply {
                        this.token = bizResult!!.token
                        this.region = bizResult.region
                        this.secret = bizResult.secret
                    })
                }
            }
        )
```

This code now crashes the app completely:
```
E/AndroidRuntime(13532): java.lang.NullPointerException: value for name access_token == null
E/AndroidRuntime(13532): 	at okhttp3.Headers.checkValue(Headers.java:280)
E/AndroidRuntime(13532): 	at okhttp3.Headers$Builder.add(Headers.java:324)
E/AndroidRuntime(13532): 	at okhttp3.Request$Builder.addHeader(Request.java:196)
E/AndroidRuntime(13532): 	at com.tuya.iotapp.network.interceptor.token.AccessTokenInterceptor.newRequestWithAccessToken(AccessTokenInterceptor.kt:56)
E/AndroidRuntime(13532): 	at com.tuya.iotapp.network.interceptor.token.AccessTokenInterceptor.intercept(AccessTokenInterceptor.kt:38)
E/AndroidRuntime(13532): 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
E/AndroidRuntime(13532): 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
```

We double-checked the appKey and appSecret and the assetId that we use here. Interestingly the following code works fine:
```
TYUserManager.userBusiness.login("...", "...", ...)
``` 
so we are pretty sure that it's not caused by the App Authorization part.

EDIT: on iOS we're getting this issue:
```
NSError *	domain: @"com.tuya.smart" - code: 1010 token invalid
```

**Comment by linhuiluo** [comment]
@jonasbark Thank u for your question. Please raise your question through our professional work order platform, attach the details, we will have someone to follow up. : https://service.console.tuya.com/8/3/create?step=4&id=01030404&source=help_sidebar .

**Comment by jonasbark** [comment]
@linhuiluo I already did so. The reason was that I was required to perform a login using the UserBusiness class.
The SDK should not crash the whole app though so maybe that's something you want to have a look at.

**Comment by linhuiluo** [comment]
@jonasbark Please raise the work order, if you have raised the work order, please provide the work order number for our side to see.

**Comment by jonasbark** [comment]
Sorry, don't have a work order but I followed up with one of your colleagues on WeChat that handle our account.
